#!/usr/bin/env node

const {runPulsar} = require('./helpers/run-atom');
const {projectPath} = require('./helpers/paths');

runPulsar({NODE_ENV: 'development', ATOM_GITHUB_BABEL_ENV: 'coverage'}, '--test', projectPath('test'));
