#!/usr/bin/env node

const {runPulsar} = require('./helpers/run-atom');
const {projectPath} = require('./helpers/paths');

runPulsar({NODE_ENV: 'development', ATOM_GITHUB_TEST_SUITE: 'snapshot'}, '--test', projectPath('test'));
